### ISSUE TITLE
Error in Sidebar.php

### ISSUE THREAD

**Issue by ReneKotnik** [groomershop/magento2-category-sidebar#3]
Hi,

I get the following error trying:
Fatal error: Uncaught Error: Call to a member function getItems() on array in /opt/lampp/htdocs/ROKO-TEST/app/code/Sebwite/Sidebar/Block/Sidebar.php:111 Stack trace: #0 /opt/lampp/htdocs/ROKO-TEST/app/code/Sebwite/Sidebar/view/frontend/templates/sidebar.phtml(10): Sebwite\Sidebar\Block\Sidebar->getCategories() #1 /opt/lampp/htdocs/ROKO-TEST/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/opt/lampp/htdo...') #2 /opt/lampp/htdocs/ROKO-TEST/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render(Object(Sebwite\Sidebar\Block\Sidebar), '/opt/lampp/htdo...', Array) #3 /opt/lampp/htdocs/ROKO-TEST/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent('render', Array) #4 /opt/lampp/htdocs/ROKO-TEST/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}(Object(Sebwite\Sidebar\Block\Sideb in /opt/lampp/htdocs/ROKO-TEST/app/code/Sebwite/Sidebar/Block/Sidebar.php on line 111

**Comment by jtomaszewski** [comment]
What magento version are you using? We're at 2.3.5 FYI. 

If u'd like to submit a PR with a fix for this, feel invited.

**Comment by mobweb** [comment]
This happens for me to on 2.4.3. My assumption is that it happens because I've got the flat category catalog turned on. There is even a TODO in that same file with a task to check if it works for flat categories.
